language: node_js
node_js:
  - "7.1"
  - "6.9"
  - "4.6"
  - "stable"

install:
  - npm install
  - npm install --prefix ./examples/convo-bot

script:
  - npm run test
  - npm test --prefix ./examples/convo-bot
